# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Copy files to S3 with the AWS CLI
      run: |
        aws s3 cp s3://samrealtimeinsightbucket/rerum.properties /home/runner/work/rerum_server/rerum_server/src/java/
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
    - name: upoad artifacts
      uses: actions/upload-artifact@master
      with:
        name: Package
        path: /home/runner/work/rerum_server/rerum_server/rerum_server.war
